context("error handling")

test_that("bad data", {
  expect_equal(1, 1)
})
